# -*- coding: utf-8 -*-
"""Omniscientrix Audio Restoration Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U53SIUqViLwn0UMkffm0tW_hYGrJq4eD
"""

# ==================================================
# Omniscientrix Instant Audio Restoration Engine v1
# ==================================================

!apt-get install ffmpeg -y

from google.colab import files
from scipy.io import wavfile
import numpy as np

# Upload audio (any format: mp3, m4a, wav, ogg)
print("Upload your audio file:")
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Convert to clean WAV
!ffmpeg -i "{filename}" -ac 1 -ar 44100 input.wav -y

# Load engine
from the_omniscientrix_intelligence_engine import Adapt, Omni

# Read audio
sr, audio = wavfile.read("input.wav")
audio = audio.astype(float)

# Apply Omniscientrix Restoration Pipeline
restored = Adapt.restore_audio(audio, Omni)

# Save & preview
wavfile.write("RESTORED_AUDIO.wav", sr, restored.astype('float32'))

print("Done! Download your cleaned audio below:")

files.download("RESTORED_AUDIO.wav")

